export const promptSuggestions = [
  'I want to improve my fitness. Find fitness plans in my notes and emails from gyms in my inbox.',
  'Did I delete an email with a birthday voucher code from Sarah?',
  'Tell me my tasks due today.',
  'What birthday presents do I need to buy for this month?',
  'What are my actions from the marketing meeting notes from today?',
  'Do I have any meeting clashes today?',
  'What was the name of the band Mike recommended to me?',
  'What time is my haircut on Saturday?',
  'Check my emails and notes for information on my house insurance.',
  'Do I have any urgent emails?',
  'Summarise my most recent note',
  'What tasks do I have to do related to my Sales Report?',
  'When’s my car due at the garage, and what car tasks are due before it?',
  'Has Abdul sent me the report yet?',
  'Have I made Tasks for all of the actions raised in my last note?',
  'When is my 1 2 1 meeting with Sam?',
  'Summarise the notes from my last three meetings',
]
